#!/usr/bin/env python3
"""Build source-ordered draft checklists; never award semantic review status.

Each source heading has its own task. Equation-image and snippet registers are
separate so an attractive chapter summary cannot conceal missing mathematics or
code. Descriptions are explicitly draft engineering interpretations. Regeneration
is deterministic and refuses to overwrite any locally edited task.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any

from lxml import etree

from .inventory_epub import HEADING_TAGS, local_name, normalized, resolve_member, visible_text, write_json


CHAPTER_OVERVIEWS = {
    1: ("Establish the financial-ML research factory, specialist production chain, failure modes and reading prerequisites.", "The book's organizational blueprint is not a complete exchange adapter, database or UI specification."),
    2: ("Transform raw financial observations into structured bars, multi-product series and sampled feature events.", "Retain raw events, point-in-time release/revision information, sampling rules and adjustment lineage."),
    3: ("Construct outcome labels, dynamic thresholds, triple barriers, side/size separation and meta-labels.", "Future outcomes are allowed in labels but must not leak into feature availability or training/evaluation separation."),
    4: ("Measure overlapping label information and construct uniqueness, bootstrap, return-attribution, time-decay and class weights.", "Overlap and weighting conventions must agree across concurrency counts, sampling and validation."),
    5: ("Derive and implement fractional differentiation while studying stationarity and retained memory.", "Different truncation schemes, warm-up rules and fitted stationarity choices are not interchangeable."),
    6: ("Study error sources, bagging, random forests, boosting and ensemble scalability in the financial-data setting.", "Dependence and redundancy qualify variance/accuracy arguments; ensembling does not repair leaked research."),
    7: ("Define financial cross-validation, diagnose leakage and reproduce purging, embargo and scoring implementations.", "Interval semantics must be explicit; historical library bugs require version-qualified reproduction."),
    8: ("Evaluate feature importance with and without substitution effects, across instruments and synthetic experiments.", "Feature usefulness, feature interaction and trading profitability are different estimands."),
    9: ("Specify purged-CV hyper-parameter searches, parameter distributions, weighted pipelines and objective-consistent scoring.", "The entire search is a selection procedure and its history must remain auditable."),
    10: ("Convert forecasts and concurrent decisions into bet sizes, discretized exposures and dynamic limit-price calculations.", "Sizing is separate from side prediction, calibration, execution feasibility and risk limits."),
    11: ("Establish why backtests mislead, why they are not a discovery tool, and how strategy selection must be evaluated.", "Simulator correctness and genuine statistical evidence are separate gates."),
    12: ("Compare walk-forward and CV evaluation and reproduce combinatorial purged CV with multiple backtest paths.", "Nonhistorical CV paths must not be presented as historically executable performance."),
    13: ("Evaluate trading rules on synthetic paths generated by the source's stochastic framework and experimental grids.", "Numerical optima are conditional on the generator, parameter range, payoff and stopping rules."),
    14: ("Build the full backtest-statistics taxonomy: characteristics, performance, runs, shortfall, efficiency, classification and attribution.", "Accounting units, estimands, annualization and multiple-trial inputs must be consistent."),
    15: ("Relate strategy precision, payout asymmetry and betting frequency to performance targets and failure probabilities.", "Probability-domain constraints and estimation uncertainty matter in both formulas and code."),
    16: ("Reproduce hierarchical risk parity, its mathematical components, numerical example and out-of-sample experiments, including appendices.", "The original observation-count assertion has a local exact counterexample; preserve it and review ERR-0001 before approval."),
    17: ("Construct structural-break and explosiveness features from CUSUM, ADF-family and martingale-based tests.", "Regression specification, window search, calibration and information availability determine each statistic."),
    18: ("Derive entropy quantities, estimators and encodings, then preserve their proposed financial applications.", "Discrete and differential entropy, finite-sample estimates and alternative encodings cannot be casually substituted."),
    19: ("Reproduce the three generations of microstructural models and catalogue additional order-flow features.", "Trade classification, event meaning, bucket clocks, units and model assumptions require source-specific treatment."),
    20: ("Reproduce vectorization, work partitioning, multiprocessing dispatch and deterministic reduction recipes.", "A native C++ translation must preserve task semantics without blindly inheriting Python runtime restrictions."),
    21: ("Reproduce discrete allocation objectives, feasible sets, exhaustive trajectory evaluation and static/dynamic numerical examples.", "Enumeration completeness, exact constraints and discretization must be checked before making solver-performance claims."),
    22: ("Preserve the HPC hardware/software discussion and every financial and nonfinancial application case, including HDF5 and in-situ processing.", "Historical case studies, regulatory discussion and hardware examples do not settle today's deployment design."),
}


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def relative_link(from_file: Path, target: Path) -> str:
    return os.path.relpath(target, from_file.parent).replace(os.sep, "/")


def write_generated(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") != text:
        raise ValueError(f"Refusing to overwrite an edited generated file: {path}")
    if not path.exists():
        path.write_text(text, encoding="utf-8")


def excerpt_with_images(element: etree._Element, member: str, task_file: Path, source: Path) -> str:
    parts: list[str] = []

    def visit(node: etree._Element) -> None:
        if not isinstance(node.tag, str):
            return
        if local_name(node) == "img":
            asset = resolve_member(member, node.get("src", ""))
            target = source / "private" / "epub" / str(asset)
            parts.append(f"![source image {Path(str(asset)).name}]({relative_link(task_file, target)})")
            return
        if local_name(node) == "br":
            parts.append(" ")
        if node.text:
            parts.append(node.text)
        for child in node:
            visit(child)
            if child.tail:
                parts.append(child.tail)

    visit(element)
    return normalized("".join(parts))


def build(root: Path) -> dict[str, Any]:
    source = root / "instructions" / "01-source"
    book = root / "instructions" / "02-book"
    manifest = json.loads((source / "manifest.json").read_text())
    sections = json.loads((source / "sections.json").read_text())
    blueprints = json.loads((book / "section_blueprints.json").read_text())
    images = json.loads((source / "images.json").read_text())
    snippets = json.loads((source / "snippets.json").read_text())
    formulas = json.loads((source / "formulas.json").read_text())
    image_map = {image["id"]: image for image in images}
    snippet_map = {snippet["id"]: snippet for snippet in snippets}
    formula_map = {formula["id"]: formula for formula in formulas}
    nodes: list[dict[str, Any]] = []
    source_trees: dict[str, list[etree._Element]] = {}
    paths: dict[str, Path] = {}
    for section in sections:
        chapter_root = book / f"ch-{section['chapter']:02d}"
        if section["kind"] == "chapter":
            path = chapter_root / "README.md"
        elif section["kind"] == "numbered_section":
            path = chapter_root / "sections" / f"{section['number']}.md"
        else:
            path = chapter_root / "apparatus" / (section["id"].split("-", 2)[2] + ".md")
        paths[section["id"]] = path
    apparatus_work = {
        "exercises": ("Reproduce every exercise and nested part as an explicit research/test task, retaining the source's order and requested outputs.", "The book does not supply a complete solution key here. Do not invent a solution and mark it source-verified."),
        "references": ("Preserve each cited reference and connect it to the claims or methods that depend on it.", "A reference entry is not evidence that the cited work has been retrieved or verified. External review needs its own record."),
        "reference": ("Preserve the reference entry and its relationship to the chapter's methods.", "Do not claim to have checked the cited work from its bibliographic title alone."),
        "bibliography": ("Preserve the bibliography as prerequisite/further-reading source apparatus.", "Bibliographic inclusion is not an implementation requirement or proof of current validity."),
        "notes": ("Review every note, preserve its anchor and link it to the relevant parent claim.", "A qualification in a note can materially change the interpretation of a formula or procedure."),
        "note": ("Review the note and preserve its anchor and parent reference.", "Do not drop notes as unimportant formatting during extraction or implementation."),
        "appendices": ("Retain the appendix container and review each numbered mathematical/code appendix.", "Appendices are in scope; they must not disappear from the chapter's completion criteria."),
    }
    for index, section in enumerate(sections):
        path = paths[section["id"]]
        if section["kind"] == "chapter":
            work, caution = CHAPTER_OVERVIEWS[section["chapter"]]
        elif section["kind"] == "numbered_section":
            blueprint = blueprints[section["number"]]
            work, caution = blueprint["work"], blueprint["caution"]
        else:
            work, caution = apparatus_work[section["id"].split("-", 2)[2]]
        member = section["document"]
        if member not in source_trees:
            tree = etree.parse(str(source / "private/epub" / member), etree.XMLParser(resolve_entities=False, no_network=True))
            source_trees[member] = list(tree.xpath('//*[local-name()="body"]')[0].iter())
        elements = source_trees[member]
        start, stop = section["position"], section["position_end_exclusive"]
        paragraph = next((element for element in elements[start:stop] if local_name(element) == "p"
                          and visible_text(element).strip()
                          and not any(local_name(ancestor) in HEADING_TAGS for ancestor in element.iterancestors())), None)
        excerpt = excerpt_with_images(paragraph, member, path, source) if paragraph is not None else ""
        source_path = source / "private/epub" / member
        anchor = section.get("anchor") or "start"
        fields = {
            "id": section["id"], "kind": section["kind"], "chapter": section["chapter"],
            "source_order": index, "source_document": member, "source_anchor": anchor,
            "source_epub_sha256": manifest["source_sha256"], "source_heading_sha256": section["source_sha256"],
            "source_page_start": section["page"], "source_page_end": section["page_end"],
            "parent": section["parent"], "status": "draft_pending_independent_review",
            "scope_excerpt_sha256": digest(excerpt),
            "required_user_requirements": ["U001", "U015", "U016", "U017", "U018", "U019", "U025", "U026"],
        }
        frontmatter = "---\n" + "\n".join(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in fields.items()) + "\n---\n\n"
        text = frontmatter + f"# {section['title']}\n\n"
        text += f"**Source:** [{member}#{anchor}]({relative_link(path, source_path)}#{anchor}); printed marker span {section['page']}–{section['page_end']}. "
        text += "These are source markers, not Word page numbers. A missing intermediate marker is not an invented page boundary.\n\n"
        text += "## Description and proposed work\n\n" + work + "\n\n"
        text += "**Classification:** draft engineering interpretation of the named source section. It is not a verbatim replacement for the source or a completed implementation specification.\n\n"
        text += "## Cautions to cross-check\n\n" + caution + "\n\n"
        text += "Keep the original notation, assumptions, index ranges, boundary behavior, units and parameter meanings. Proposed corrections belong in the errata register, never in the immutable source.\n\n"
        text += "## Source anchor excerpt\n\n"
        if excerpt:
            text += "> " + excerpt + "\n\n"
            text += "This is the complete first eligible paragraph of the direct section span, not a summary of the whole section. Image placements remain linked to the original assets; inline typography is normalized for this excerpt. Read the complete linked XHTML span, all nested list parts, notes and assets before approval.\n\n"
        else:
            text += "This direct span has no eligible introductory paragraph. Review its headings, lists, images and child sections in the source; absence of an excerpt does not mean absence of content.\n\n"
        children = [candidate for candidate in sections if candidate["parent"] == section["id"]]
        if children:
            text += "## Source-order children\n\n"
            for child in children:
                text += f"- [{child['title']}]({relative_link(path, paths[child['id']])})\n"
            text += "\nParent completion additionally requires the child records; reading the introduction alone does not complete the subtree.\n\n"
        text += "## Evidence inventory for this direct span\n\n"
        text += f"Source block records: **{len(section['block_ids'])}** (nested container records may overlap; never sum them as a word count). "
        text += f"Image placements: **{len(section['image_ids'])}**. Commented MathML records: **{len(section['math_comment_ids'])}**. Native tables: **{len(section['table_ids'])}**. Snippet headings: **{len(section['snippet_ids'])}**.\n\n"
        for identifier in section["image_ids"]:
            image = image_map[identifier]
            target = source / "private/epub" / str(image["asset"])
            text += f"- `{identifier}` — {image['kind']}; [{Path(str(image['asset'])).name}]({relative_link(path, target)}), source page {image['page']}; SHA-256 `{image['sha256']}`.\n"
        for identifier in section["snippet_ids"]:
            snippet_path = book / f"ch-{section['chapter']:02d}/snippets/{identifier}.md"
            text += f"- `{identifier}` — [{snippet_map[identifier]['title']}]({relative_link(path, snippet_path)}).\n"
        for identifier in section["table_ids"]:
            text += f"- `{identifier}` — native HTML table; review cells, row/column labels and notes in the source.\n"
        text += "\n## TODO and acceptance gates\n\n"
        text += "- [x] Source heading, direct span and linked asset IDs mechanically inventoried. This is **not** semantic approval.\n"
        text += "- [ ] Independently read the entire source span in book order, including figures, captions, notes, tables and every exercise/list part.\n"
        text += "- [ ] Cross-check this description, proposed work and caution against that span; record omissions or unsupported interpretations.\n"
        text += "- [ ] For each mathematical expression, compare its rendered form, notation and context; complete the symbol/domain/unit glossary, assumptions, derivation and boundary tests. Explicitly record not-applicable items.\n"
        text += "- [ ] For each code artifact, verify transcription from its original image/text and identify version-specific behavior without changing the original.\n"
        text += "- [ ] Define the reference result and independent oracle; reproduce the source example or document why an exact reproduction is not specified.\n"
        text += "- [ ] Where computation is applicable, compare readable Python/reference and C++ implementations, including adversarial inputs, precision limits and any approved errata.\n"
        text += "- [ ] Evaluate performance only after equivalence passes; retain hardware, versions, workload, latency distribution, memory and accuracy evidence.\n"
        text += "- [ ] Independent reviewer approves the evidence, or records an explicit blocker; update the review record rather than auto-checking this list.\n\n"
        text += "## Navigation and provenance\n\n"
        navigation = []
        if index:
            prior = sections[index - 1]
            navigation.append(f"[Previous: {prior['title']}]({relative_link(path, paths[prior['id']])})")
        if index + 1 < len(sections):
            following = sections[index + 1]
            navigation.append(f"[Next: {following['title']}]({relative_link(path, paths[following['id']])})")
        text += " | ".join(navigation) + "\n\n"
        text += f"[Review protocol]({relative_link(path, root / 'instructions/03-crosschecks/REVIEW_PROTOCOL.md')}) | "
        text += f"[Errata]({relative_link(path, root / 'instructions/03-crosschecks/ERRATA.md')}) | "
        text += f"[Full source manifest]({relative_link(path, source / 'manifest.json')})\n"
        write_generated(path, text)
        nodes.append({**fields, "title": section["title"], "path": str(path.relative_to(root)), "md_sha256": digest(text),
                      "block_ids": section["block_ids"], "image_ids": section["image_ids"],
                      "math_comment_ids": section["math_comment_ids"], "snippet_ids": section["snippet_ids"],
                      "table_ids": section["table_ids"]})

    equation_nodes = []
    for image in images:
        if image["kind"] not in {"inline_equation", "display_equation"}:
            continue
        chapter = int(re.search(r"c(\d+)", image["document"]).group(1))
        path = book / f"ch-{chapter:02d}/equations/{image['id']}.md"
        linked_math = [formula for formula in formulas if formula["rendered_asset"] == image["asset"]]
        text = f"# {image['id']} — {Path(image['asset']).name}\n\n"
        text += f"Source: `{image['document']}`, section `{image['section_id']}`, printed marker `{image['page']}`.\n\n"
        text += f"![Original rendered equation]({relative_link(path, source / 'private/epub' / image['asset'])})\n\n"
        text += f"**Original image SHA-256:** `{image['sha256']}`.\n\n"
        text += "**Status:** preserved; mathematical transcription, image/MathML agreement and derivation review are not approved.\n\n"
        if linked_math:
            text += "## Commented MathML retained in the EPUB\n\nThis is hidden source markup, not independent proof that it matches the rendered equation.\n\n"
            for formula in linked_math:
                text += f"Record `{formula['id']}`; SHA-256 `{formula['sha256']}`.\n\n```xml\n{formula['mathml']}\n```\n\n"
        else:
            text += "**No matched commented MathML exists in the supplied source.** Read the original image directly; do not guess the missing editable representation.\n\n"
        text += "## TODO\n\n- [x] Preserve and hash the original rendered image.\n- [ ] Verify every symbol, subscript, superscript, operator, limit and boundary against the image.\n- [ ] Define all symbols, domains, units and assumptions from the surrounding source.\n- [ ] Derive or independently verify the result; record counterexamples and errata separately.\n- [ ] Specify exact/high-precision reference cases and numerical error bounds before native implementation.\n"
        write_generated(path, text)
        equation_nodes.append({"id": image["id"], "path": str(path.relative_to(root)), "source_asset_sha256": image["sha256"],
                               "matched_mathml_count": len(linked_math), "status": "preserved_not_mathematically_verified", "md_sha256": digest(text)})
    snippet_nodes = []
    for snippet in snippets:
        chapter = int(re.search(r"c(\d+)", snippet["document"]).group(1))
        path = book / f"ch-{chapter:02d}/snippets/{snippet['id']}.md"
        text = f"# {snippet['title']}\n\nSource: `{snippet['document']}`; section `{snippet['section_id']}`; printed marker `{snippet['page']}`.\n\n"
        if snippet["image_assets"]:
            for asset in snippet["image_assets"]:
                text += f"![Original code artifact]({relative_link(path, source / 'private/epub' / asset)})\n\n"
        else:
            text += "This snippet is not represented by an image in its enclosing source section. Read the original text/code and surrounding structure at the source locator; do not infer that it is absent.\n\n"
        text += "## TODO\n\n- [x] Preserve source locator and original code representation.\n- [ ] Transcribe every token and indentation level where transcription is required; compare to the original.\n- [ ] Record imports, dependencies, versions, implied inputs, output types and unhandled edge cases.\n- [ ] Keep the literal original separate from a readable, typed, runnable reference version.\n- [ ] Compare source equations, narrative algorithm and executable behavior; open an erratum for discrepancies.\n- [ ] Build analytical/adversarial tests and an independent oracle.\n- [ ] Port approved semantics to C++ where justified; measure rather than assume equivalence and speed.\n\nNo code in a source snippet is executed by extraction or documentation generation.\n"
        write_generated(path, text)
        snippet_nodes.append({"id": snippet["id"], "path": str(path.relative_to(root)), "status": "preserved_transcription_review_pending", "md_sha256": digest(text)})

    spine = json.loads((source / "spine.json").read_text())
    ancillary = []
    for item in spine:
        if item["chapter"] is not None:
            continue
        path = book / "front-and-back-matter" / f"{item['id']}.md"
        text = f"# Source apparatus: {item['path']}\n\nSpine order: `{item['spine_index']}`.\n\n"
        text += f"[Original XHTML]({relative_link(path, source / 'private/epub' / item['path'])})\n\n"
        text += "This source document is retained in the original archive and Word transcription. Covers, front matter, part dividers, contents, index and end matter are not discarded merely because they are not numbered chapters.\n\n"
        text += "- [x] Capture the source document in spine order.\n- [ ] Review all text, images, navigation and attribution against the source.\n- [ ] Record applicability without inventing product requirements from publication apparatus.\n"
        write_generated(path, text)
        ancillary.append({"id": item["id"], "path": str(path.relative_to(root)), "md_sha256": digest(text)})
    index = "# AFML book-first checklist index\n\n"
    index += "**Status: complete mechanical inventory; draft interpretations; independent semantic and mathematical review is not complete.**\n\n"
    index += "The supplied edition has 22 chapters, 280 numbered sections and 67 unnumbered chapter-apparatus headings. Chapter cards, section cards, equation-image records and snippet records are distinct so coverage cannot be inferred from a single chapter summary. Original text and images remain the authority.\n\n"
    index += "| Chapter | Scope | Entry |\n|---|---|---|\n"
    for chapter in range(1, 23):
        title = next(section["title"] for section in sections if section["id"] == f"CH-{chapter:02d}")
        index += f"| {chapter} | {title} | [Checklist](ch-{chapter:02d}/README.md) |\n"
    index += "\n## Read before using\n\nThe first-paragraph anchor in a task is not exhaustive analysis. A checkbox for inventory is not a checkbox for understanding or correctness. Printed page markers are preserved, including a separate register of missing marker numbers; Word reflows the book. Inline mathematical expressions rendered as ordinary text remain in the full source even when they have no equation-image record.\n\n"
    index += "Review must proceed through source, description, equations/snippets, reference results, independent tests, native equivalence and measured performance. Unresolved ambiguity or errata blocks approval.\n"
    write_generated(book / "README.md", index)
    output = {"schema_version": 1, "source_epub_sha256": manifest["source_sha256"], "sections": nodes,
              "equation_images": equation_nodes, "snippets": snippet_nodes, "ancillary_documents": ancillary}
    write_json(book / "task_index.json", output)
    report = {"section_task_count": len(nodes), "numbered_section_task_count": sum(n["kind"] == "numbered_section" for n in nodes),
              "chapter_task_count": sum(n["kind"] == "chapter" for n in nodes), "equation_image_task_count": len(equation_nodes),
              "snippet_task_count": len(snippet_nodes), "ancillary_document_task_count": len(ancillary),
              "semantic_reviews_approved": 0, "mathematical_reviews_approved": 0}
    write_json(root / "instructions/reports/checklist_build.json", report)
    print(json.dumps(report, indent=2))
    return report

# CLI entry point: instructions/tools/rebuild_private_source.py.
